name: conda-forge-bot
channels:
  - conda-forge
platforms:
  - linux-64
dependencies:
  - backoff
  - bcrypt
  - cachecontrol
  - cachetools
  - click
  - conda >=25
  - conda-build >=25
  - conda-forge-feedstock-ops >=0.18.8
  - conda-forge-metadata >=2026.9.3
  - conda-forge-pinning
  - conda-libmamba-solver
  - conda-lock
  - conda-package-handling
  - conda-recipe-manager >=0.10.6
  - conda-smithy >=2026.5.29
  - curl
  - dateparser
  - distributed
  - fastapi
  - feedparser
  - frozendict
  - git !=2.50
  - github3.py
  - grayskull >=3.1.1
  - jinja2
  - lockfile
  - mamba >=0.23
  - mitmproxy
  - msgpack-python
  - networkx !=2.8.1
  - orjson
  - packaging
  - psutil
  - py-rattler>=0.22.0,<0.26.0a0
  - pydantic
  - pydantic-extra-types
  - pydantic-settings
  - pygithub
  - pymongo
  - pynamodb
  - python-dateutil
  - python-graphviz
  - rattler-build >=0.74,<0.75.0a0
  - rattler-build-conda-compat >=1.4.13,<2
  - requests
  - ruamel.yaml
  - ruamel.yaml.jinja2
  - scipy
  - setuptools
  - stopit
  - streamz
  - tar
  - tqdm
  - wget
  - wurlitzer
  # build
  - python=3.12
  - pip
  - python-build
  - setuptools_scm >=8
  # test
  - codecov
  - mypy
  - pre-commit
  - pytest =9
  - pytest-cov
  - pytest-env
  - pytest-retry
  - pytest-split
  - pytest-xdist
  - pytest-xprocess
  - requests-mock
