name: release

on:
  workflow_dispatch: null
  push:
    branches:
      - main

env:
  PY_COLORS: "1"
  REGISTRY: quay.io
  IMAGE_NAME: condaforge/conda-forge-tick

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: free disk space
        uses: endersonmenezes/free-disk-space@7901478139cff6e9d44df5972fd8ab8fcade4db1 # v3
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          rm_cmd: "rmz"

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@d7c9bd84e824b79d2af72a2d4196c7f4300d3476 # v3.0.0
        with:
          environment-file: conda-lock.yml
          environment-name: conda-forge-bot
          condarc-file: autotick-bot/condarc

      - name: stop me if needed
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          python autotick-bot/stop_me_if_needed.py

      - name: compute next version
        id: version
        if: ${{ ! env.CI_SKIP }}
        run: |
          echo "recent version tags: "$(git tag --sort=committerdate | tail -4)
          NEXT=$(python autotick-bot/compute_next_version.py)
          echo "next version: ${NEXT}"
          echo "NEXT=${NEXT}" >> "$GITHUB_OUTPUT"

      - name: build docker image
        if: ${{ ! env.CI_SKIP }}
        uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: conda-forge-tick
          tags: latest ${{ steps.version.outputs.NEXT }}
          containerfiles: |
            ./Dockerfile
          extra-args: |
            --no-cache
          build-args: |
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.version.outputs.NEXT }}

      - name: push docker image to quay.io
        if: ${{ ! env.CI_SKIP }}
        uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: conda-forge-tick
          tags: latest ${{ steps.version.outputs.NEXT }}
          registry: quay.io/condaforge
          username: conda_forge_daemon
          password: ${{ secrets.CF_DAEMON_QUAY_PASSWORD }}

      - name: tag and release
        if: ${{ ! env.CI_SKIP }}
        run: |
          python autotick-bot/release.py "${{ steps.version.outputs.NEXT }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
