name: release

on:
  workflow_dispatch: null
  push:
    branches:
      - main
  pull_request: null
  merge_group: null

env:
  PY_COLORS: "1"
  REGISTRY: quay.io
  IMAGE_NAME: condaforge/conda-forge-tick

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: release
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: free disk space
        uses: endersonmenezes/free-disk-space@2a22f8c59cae9cddae7194b33e6b92d023b2b4b8 # v4.0.0
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          rm_cmd: "rmz"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          environment-file: conda-lock.yml
          environment-name: conda-forge-bot
          condarc-file: autotick-bot/condarc

      - name: stop me if needed
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          python autotick-bot/stop_me_if_needed.py

      - name: compute next version
        id: version
        if: ${{ (! env.CI_SKIP) || github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        run: |
          echo "recent version tags: "$(git tag --sort=committerdate | tail -4)
          NEXT=$(python autotick-bot/compute_next_version.py)
          echo "next version: ${NEXT}"
          echo "NEXT=${NEXT}" >> "$GITHUB_OUTPUT"

      - name: build docker image
        if: ${{ (! env.CI_SKIP) || github.event_name == 'pull_request' || github.event_name == 'merge_group' }}
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        with:
          image: conda-forge-tick
          tags: latest ${{ steps.version.outputs.NEXT }}
          containerfiles: |
            ./Dockerfile
          extra-args: |
            --no-cache
            --squash
          build-args: |
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.version.outputs.NEXT }}

      - name: push docker image to quay.io
        if: ${{ (! env.CI_SKIP) && github.event_name != 'pull_request' && github.event_name != 'merge_group' }}
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        with:
          image: conda-forge-tick
          tags: latest ${{ steps.version.outputs.NEXT }}
          registry: quay.io/condaforge
          username: conda_forge_daemon
          password: ${{ secrets.CF_DAEMON_QUAY_PASSWORD }}

      - name: tag and release
        if: ${{ (! env.CI_SKIP) && github.event_name != 'pull_request' && github.event_name != 'merge_group' }}
        run: |
          python autotick-bot/release.py "${{ steps.version.outputs.NEXT }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
