name: test-model

on:
  workflow_dispatch:
  schedule:
    - cron: "10 8 * * *" # daily at 8:10 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PY_COLORS: "1"
  PYTHONUNBUFFERED: "1"

jobs:
  test-model:
    name: test-model
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -leo pipefail {0}

    steps:
      - name: free disk space
        uses: endersonmenezes/free-disk-space@2a22f8c59cae9cddae7194b33e6b92d023b2b4b8 # v4.0.0
        with:
          remove_android: true
          remove_dotnet: true
          remove_haskell: true
          rm_cmd: "rmz"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: conda-forge-bot

      - uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
        with:
          environment-file: conda-forge-bot/conda-lock.yml
          environment-name: conda-forge-bot
          condarc-file: conda-forge-bot/autotick-bot/condarc

      - name: configure conda, install code, and clone cf-graph
        run: |
          source conda-forge-bot/autotick-bot/install_bot_code.sh

      - name: run pytest (model)
        run: |
          cd cf-graph
          # for pull requests, a failed model test should not be a failed check
          # this is a hack around the absence of https://github.com/orgs/community/discussions/15452
          pytest \
            --durations 10 \
            ../conda-forge-bot/tests_model ${{ github.event_name == 'pull_request' && '|| [ $? = 1 ]' || '' }}
